export {default as Logo} from './Logo';
export {default as Sidebar} from './Sidebar';
export {default as Navbar} from './Navbar';
export {default as PatientInformation} from './PatientInformation';
export {default as Table} from './Table';
export {default as Appointments} from './Appointment';
export {default as Medication} from './Medication';
export {default as Laboratory} from './Laboratory';
export {default as AppointmentTable} from './AppoitmentTable';